# Generated by Django 3.0.5 on 2020-08-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brandmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='cost_price',
            field=models.FloatField(blank=0.0, default=0.0),
        ),
    ]
