# Generated by Django 3.0.5 on 2020-08-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_brandmodel_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='initial_discount',
            field=models.FloatField(blank=0.0, default=0.0, null=True),
        ),
    ]
