# Generated by Django 3.0.5 on 2020-08-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200809_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
