# Generated by Django 3.0.5 on 2020-08-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200807_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
