# Generated by Django 3.0.5 on 2020-08-07 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20200807_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 7)),
        ),
    ]
