# Generated by Django 3.0.5 on 2020-08-10 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20200809_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 10), null=True),
        ),
    ]
