# Generated by Django 3.0.5 on 2020-08-12 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20200810_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 12), null=True),
        ),
    ]
