# Generated by Django 3.0.5 on 2020-08-10 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0003_auto_20200809_0946'),
        ('customers', '0010_auto_20200810_1628'),
        ('brands', '0002_brandmodel_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_discount', models.FloatField(blank=0.0, default=0.0)),
                ('total_amount', models.FloatField(blank=0.0, default=0.0)),
                ('amount_payable', models.FloatField(blank=0.0, default=0.0)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2020, 8, 10, 17, 5, 46, 418218), null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customer')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.PaymentModel')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brands.BrandModel')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='receipts.Receipts')),
            ],
        ),
    ]
