# Generated by Django 3.0.5 on 2020-08-10 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sales',
            name='selling_price',
            field=models.FloatField(blank=0.0, default=0.0),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 17, 50, 45, 997068), null=True),
        ),
    ]
