# Generated by Django 3.0.5 on 2020-08-12 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_auto_20200810_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 15, 33, 59, 752445), null=True),
        ),
    ]
